/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";
import type RouterOutputs from "~/utils/api";
import { UserButton } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";

dayjs.extend(relativeTime);

function Input({name, placeholder, method="text"}: {name: string, placeholder: string, method?: string}) {
  return (
    <div className="flex gap-2 p-2 w-full">
      <label className="flex">{name}</label>
      <input placeholder={placeholder} className="grow outline-none w-full bg-transparent" type={method} />
    </div>
  )
}

type PostWithUser = RouterOutputs["listings"]["getAll"][number]; 

function PostView(props: PostWithUser) {

  const { post: listing, author } = props
  
  return (
    <div key={listing.id} className="p-5 border-b border-blue-400 flex flex-col gap-3">
        <Image src={author.profileImageUrl} className="w-14 h-14 rounded-full" alt="Profile Image URL" width={56} height={56} />
        <div className="flex flex-col">
          <div className="flex gap-4">
            <span>{`${author.firstName} ${author.lastName} - ${dayjs(listing.created_at).fromNow()}`}</span>
            <span className="font-thin"></span>
          </div>
          <div className="flex flex-col">
            <span>{listing.name}</span>
            <span>{listing.desc}</span>
          </div>
        </div>
    </div>
  )
}

function CreatePostWizard() {
  const { user } = useUser();

  if(!user) return <div>No user!</div>

  const verified = true;

  const { data } = api.user.userInfo.useQuery({email: user.primaryEmailAddress!.emailAddress})

  if(!data?.v) return <div>Not Verified</div>

  return (
    <div className="flex flex-col gap-3 p-5 border-b border-blue-500">
      {JSON.stringify(data)}
      <Input name="Name" placeholder="Enter the name of the hike" />
      <Input name="Description" placeholder="Describe and explain the hike" />
      <Input name="Route" placeholder="Enter the route of the hike"  />
      <Input name="Date" placeholder="" method="date" />
    </div>
  )
}

export default function Home() {
  const { data, isLoading } = api.listings.getAll.useQuery();

  const user = useUser();

  console.log(user)

  if(isLoading) return (<div>Loading...</div>)

  if(!data) return (<div>Something went wronga</div>)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center h-screen bg-emerald-200">
        <div className="w-full border-x border-blue-400 h-full md:max-w-2xl">
          <div className="py-2 border-b border-blue-500">
            {!!user.isSignedIn && 
              <div className="flex justify-center">
                <UserButton />
              </div>}
            {!user.isSignedIn && <SignInButton mode="modal" />}
          </div>
          <CreatePostWizard />
          <div className="border-b border-emerald-400">
          {data?.map((fullPost) => (
            <PostView key={fullPost.post.id } {...fullPost} />
          ))}
        </div>
        </div>
    </div>
    </>
  );
}
